name: xAImed
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
   # basic programs
   - python=3.10
   - pip
   # scientific python base packages
   - numpy
   - pandas
   - scipy
   # jupyter notebooks
   - ipykernel
   - notebook
   - jupyterlab
   - nb_conda_kernels
   - ipympl
   # python visualization
   - matplotlib
   - seaborn
   # machine learning
   - pytorch>=2.1
   - pytorch-cuda=11.8
   - torchvision
   - scikit-learn
   - pip:
      # data processing
      - medmnist
      # xAI
      - captum
      # adversarial attacks
      - torchattacks
      # this package
      - -e . 
